# Generated by Django 3.2.16 on 2022-11-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribtion',
            options={'ordering': ['-user'], 'verbose_name': 'Подписка1', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', 'email'], 'verbose_name': 'Пользователь1', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
